# Generated by Django 4.2.3 on 2024-02-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("registration_link", models.TextField(blank=True, null=True)),
                ("mode", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("total_regs", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=500)),
                ("department", models.CharField(max_length=500)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="faculty_imgs"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("College", models.CharField(max_length=500)),
                ("year_of_study", models.IntegerField()),
                ("role", models.CharField(max_length=500)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="member_imgs"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sponsors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "association",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="sponsor_imgs"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitee_website.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event_Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="event_media"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitee_website.event",
                    ),
                ),
            ],
        ),
    ]
